"""Self-contained HTML dashboard generated from the validation DB.

Read-only view layer: renders verdicts, evidence, and the forward paper
book into one dependency-free HTML file (inline CSS/JS, no external
requests). Regenerated by the daily tracker run.
"""
import html
import json
import math
import time
from datetime import datetime, timezone

import numpy as np

from . import config, events, futures_exec, gauntlet, stats


def _f(x, dp=2, suffix="%", mul=100.0):
    if x is None or (isinstance(x, float) and (math.isnan(x) or math.isinf(x))):
        return "–"
    return f"{x * mul:+.{dp}f}{suffix}" if suffix == "%" else f"{x:.{dp}f}"


def _n(x, dp=3):
    if x is None or (isinstance(x, float) and (math.isnan(x) or math.isinf(x))):
        return "–"
    return f"{x:.{dp}f}"


def _ts(ms):
    if not ms:
        return "–"
    return datetime.fromtimestamp(ms / 1000, tz=timezone.utc).strftime("%Y-%m-%d")


def gather(conn):
    evs = events.load_events(conn)
    hb = gauntlet.run_hb(conn, evs)
    fx = None
    if conn.execute("SELECT COUNT(*) FROM perp_meta").fetchone()[0]:
        fx = futures_exec.verdict(futures_exec.run(conn, evs), hb["matrices"])

    n, lo, hi, with_ann, delisted = conn.execute(
        "SELECT COUNT(*), MIN(first_trade_time), MAX(first_trade_time), "
        "SUM(CASE WHEN announcement_time IS NOT NULL THEN 1 ELSE 0 END), "
        "SUM(CASE WHEN listing_status='DELISTED' THEN 1 ELSE 0 END) "
        "FROM events WHERE included=1").fetchone()

    mat = hb["matrices"]
    M, names = mat["net_short"], mat["config_names"]
    grid = {}
    for j, name in enumerate(names):
        col = M[:, j]
        col = col[~np.isnan(col)]
        e, h = name.split("|")
        if len(col):
            grid[(e, h)] = {"n": int(len(col)), "mean": float(col.mean()),
                            "median": float(np.median(col)),
                            "win": float((col > 0).mean()),
                            "sr": stats.sharpe(col)}

    j = names.index("+1h|14d")
    col = M[:, j]
    years = {}
    for i, ev in enumerate(mat["events"]):
        y = datetime.fromtimestamp(
            ev["first_trade_time"] / 1000, tz=timezone.utc).year
        v = col[i]
        if not np.isnan(v):
            years.setdefault(y, []).append(float(v))
    regime = [
        {"year": y, "n": len(v), "mean": float(np.mean(v)),
         "win": float(np.mean([x > 0 for x in v]))}
        for y, v in sorted(years.items())
    ]

    rev = hb["reversion"]
    rev_rows = []
    for k, name in enumerate(rev["config_names"]):
        c = rev["net_long"][:, k] if rev["net_long"].size else np.array([])
        c = c[~np.isnan(c)]
        rev_rows.append({"name": name, "n": int(len(c)),
                         "mean": float(c.mean()) if len(c) else None,
                         "win": float((c > 0).mean()) if len(c) else None})

    book = [
        dict(zip(("symbol", "ft", "perp", "status", "fill", "funding",
                  "total", "spot"), r))
        for r in conn.execute(
            "SELECT symbol, first_trade_time, perp_symbol, status, "
            "fill_return, funding_return, total_return, spot_return "
            "FROM paper_trades ORDER BY first_trade_time")
    ]

    return {
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "summary": {"n": n, "lo": lo, "hi": hi, "with_ann": with_ann,
                    "delisted": delisted},
        "hb": hb, "fx": fx, "grid": grid, "regime": regime,
        "reversion": rev_rows, "book": book,
    }


CSS = """
:root{
  --bg:#FAFAF7; --panel:#FFFFFF; --line:#E4E2DB; --ink:#20242A;
  --ink2:#5C6470; --ink3:#8B909A; --pos:#0E7E9E; --neg:#C2562B;
  --pos-tint:#0E7E9E; --neg-tint:#C2562B;
  --pass:#2E7D45; --pass-bg:#E5F0E8; --fail:#B03A2E; --fail-bg:#F5E6E3;
  --wait:#5C6470; --wait-bg:#ECEBE6; --accent:#0E7E9E;
}
@media (prefers-color-scheme: dark){:root{
  --bg:#15181B; --panel:#1C2024; --line:#2C3138; --ink:#E6E4DF;
  --ink2:#9BA1AA; --ink3:#6E747E; --pos:#2E93B5; --neg:#D5713B;
  --pos-tint:#2E93B5; --neg-tint:#D5713B;
  --pass:#4C9A63; --pass-bg:#1F2E24; --fail:#C4574A; --fail-bg:#33221F;
  --wait:#9BA1AA; --wait-bg:#24282D; --accent:#2E93B5;
}}
:root[data-theme="dark"]{
  --bg:#15181B; --panel:#1C2024; --line:#2C3138; --ink:#E6E4DF;
  --ink2:#9BA1AA; --ink3:#6E747E; --pos:#2E93B5; --neg:#D5713B;
  --pos-tint:#2E93B5; --neg-tint:#D5713B;
  --pass:#4C9A63; --pass-bg:#1F2E24; --fail:#C4574A; --fail-bg:#33221F;
  --wait:#9BA1AA; --wait-bg:#24282D; --accent:#2E93B5;
}
:root[data-theme="light"]{
  --bg:#FAFAF7; --panel:#FFFFFF; --line:#E4E2DB; --ink:#20242A;
  --ink2:#5C6470; --ink3:#8B909A; --pos:#0E7E9E; --neg:#C2562B;
  --pos-tint:#0E7E9E; --neg-tint:#C2562B;
  --pass:#2E7D45; --pass-bg:#E5F0E8; --fail:#B03A2E; --fail-bg:#F5E6E3;
  --wait:#5C6470; --wait-bg:#ECEBE6; --accent:#0E7E9E;
}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
  font:15px/1.55 system-ui,"Segoe UI",Roboto,sans-serif;}
.mono{font-family:ui-monospace,"SF Mono","Cascadia Code",Consolas,Menlo,monospace;
  font-variant-numeric:tabular-nums;}
.wrap{max-width:1080px;margin:0 auto;padding:28px 20px 80px;}
header{display:flex;flex-wrap:wrap;align-items:baseline;gap:10px 16px;
  border-bottom:2px solid var(--ink);padding-bottom:14px;margin-bottom:26px;}
header h1{font-size:21px;margin:0;letter-spacing:.01em}
header .sub{color:var(--ink2);font-size:13px}
header .stamp{margin-left:auto;color:var(--ink3);font-size:12px}
.eyebrow{font-family:ui-monospace,Consolas,monospace;font-size:11px;
  letter-spacing:.14em;text-transform:uppercase;color:var(--accent);
  margin:34px 0 10px;}
section p.note{color:var(--ink2);font-size:13.5px;max-width:72ch;margin:8px 0 0}
table{border-collapse:collapse;width:100%;font-size:13.5px}
.scroll{overflow-x:auto;border:1px solid var(--line);border-radius:6px;
  background:var(--panel)}
th{font-family:ui-monospace,Consolas,monospace;font-size:11px;
  letter-spacing:.08em;text-transform:uppercase;color:var(--ink2);
  text-align:left;padding:9px 12px;border-bottom:1px solid var(--line);
  white-space:nowrap}
td{padding:8px 12px;border-bottom:1px solid var(--line);vertical-align:top}
tr:last-child td{border-bottom:none}
td.num,th.num{text-align:right;font-family:ui-monospace,Consolas,monospace;
  font-variant-numeric:tabular-nums;white-space:nowrap}
.pill{display:inline-block;padding:2px 9px;border-radius:99px;font-size:11.5px;
  font-family:ui-monospace,Consolas,monospace;letter-spacing:.05em;
  font-weight:600;white-space:nowrap}
.pill.pass{color:var(--pass);background:var(--pass-bg)}
.pill.fail{color:var(--fail);background:var(--fail-bg)}
.pill.wait{color:var(--wait);background:var(--wait-bg)}
.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));
  gap:10px;margin-top:6px}
.tile{background:var(--panel);border:1px solid var(--line);border-radius:6px;
  padding:12px 14px}
.tile .v{font-family:ui-monospace,Consolas,monospace;font-size:22px;
  font-weight:650;font-variant-numeric:tabular-nums}
.tile .k{color:var(--ink2);font-size:12px;margin-top:2px;line-height:1.35}
.tile .v.pos{color:var(--pos)} .tile .v.neg{color:var(--neg)}
.verdict-row td:first-child{font-weight:600}
.meaning{color:var(--ink2);font-size:12.5px}
.cell{position:relative}
.bars{display:flex;align-items:flex-end;gap:14px;padding:18px 16px 6px;
  background:var(--panel);border:1px solid var(--line);border-radius:6px;
  overflow-x:auto}
.bargrp{display:flex;flex-direction:column;align-items:center;gap:5px;
  min-width:56px}
.barval{font-family:ui-monospace,Consolas,monospace;font-size:11.5px;
  font-variant-numeric:tabular-nums;color:var(--ink2)}
.barstem{width:26px;border-radius:3px 3px 0 0}
.barlbl{font-family:ui-monospace,Consolas,monospace;font-size:11px;
  color:var(--ink2)}
.barn{font-size:10px;color:var(--ink3)}
.callout{border:1px solid var(--line);border-left:3px solid var(--neg);
  background:var(--panel);border-radius:4px;padding:12px 16px;
  font-size:13.5px;margin-top:12px;max-width:100%}
.callout.info{border-left-color:var(--accent)}
.foot{margin-top:44px;border-top:1px solid var(--line);padding-top:16px;
  color:var(--ink2);font-size:12.5px;max-width:78ch}
.foot ul{margin:8px 0 0;padding-left:18px}
.foot li{margin-bottom:5px}
@media (prefers-reduced-motion: no-preference){
  .tile,.pill{transition:background .15s}
}
"""


def _pill(label):
    cls = {"REAL EDGE": "pass", "GHOST": "fail"}.get(label, "wait")
    return f'<span class="pill {cls}">{html.escape(label)}</span>'


def _tint(mean, clamp=0.20):
    """Cell background: polarity hue at opacity scaled to |mean| (clamped)."""
    if mean is None:
        return ""
    a = min(abs(mean), clamp) / clamp * 0.30
    var = "--pos-tint" if mean >= 0 else "--neg-tint"
    return (f'style="background:color-mix(in srgb, var({var}) {a*100:.0f}%, '
            f'transparent)"')


def render(d):
    s, hb, fx = d["summary"], d["hb"], d["fx"]
    st = hb["stages"]
    desc = hb["descriptive"]
    s3, s5 = st[2], st[4]
    best_cell = s3.get("best_cell", "+1h|14d")

    # --- verdict ledger -----------------------------------------------------
    fx_verdict = fx["verdict"] if fx else "NOT TESTED"
    fx_why = fx["why"] if fx else "futures leg not ingested"
    ledger_rows = f"""
<tr class="verdict-row"><td>H-B · fade the listing (spot signal)</td>
 <td>{_pill(hb['verdict'])}</td>
 <td class="meaning">Listings dump after the first-hour pump. All six gauntlet
 stages passed; confidence <b>marginal</b>. Spot-actionable form: do not buy
 listings.</td></tr>
<tr class="verdict-row"><td>H-B · short side on futures (D3)</td>
 <td>{_pill(fx_verdict)}</td>
 <td class="meaning">{html.escape(fx_why)}. Funding modeled from actual
 archive rates; sizing is existential (uncapped squeeze tail).</td></tr>
<tr class="verdict-row"><td>H-C · pre-listing drift</td>
 <td>{_pill('NOT TESTED')}</td>
 <td class="meaning">Needs off-Binance price history — tokens do not trade on
 Binance before listing.</td></tr>
<tr class="verdict-row"><td>H-A · accumulation predicts listing</td>
 <td>{_pill('NOT TESTED')}</td>
 <td class="meaning">Requires a never-listed control group (hard block 8);
 tested last by design.</td></tr>"""

    # --- stage battery ------------------------------------------------------
    stage_rows = ""
    for stg in st:
        p = stg.get("pass")
        pill = ('<span class="pill wait">—</span>' if p is None
                else f'<span class="pill {"pass" if p else "fail"}">'
                     f'{"PASS" if p else "FAIL"}</span>')
        stage_rows += (f'<tr><td class="mono">{html.escape(stg["name"])}</td>'
                       f'<td>{pill}</td>'
                       f'<td class="mono" style="font-size:12px">'
                       f'{html.escape(str(stg.get("key_stat", "–")))}</td></tr>')

    # --- base-rate tiles ----------------------------------------------------
    tiles = f"""
<div class="tiles">
 <div class="tile"><div class="v">{desc['frac_peak_within_24h']*100:.0f}%</div>
  <div class="k">of listings peak within the first 24 hours</div></div>
 <div class="tile"><div class="v">{desc['median_max_drawdown_14d']*100:.0f}%</div>
  <div class="k">median max drawdown inside 14 days</div></div>
 <div class="tile"><div class="v">{desc['frac_below_entry_at_14d']*100:.0f}%</div>
  <div class="k">trade below their first-hour price 14 days later</div></div>
 <div class="tile"><div class="v pos">{_f(s5.get('net_mean'))}</div>
  <div class="k">net short return per event, best cell {html.escape(best_cell)}
  (fees + slippage in)</div></div>
 <div class="tile"><div class="v">{s3.get('n','–')}</div>
  <div class="k">events behind the verdict ({s['delisted']} now-dead tokens
  kept — survivorship-complete)</div></div>
</div>"""

    # --- grid matrix ---------------------------------------------------------
    entries = list(config.ENTRY_OFFSETS_MS)
    horizons = list(config.HORIZONS_MS)
    grid = d["grid"]
    head = "".join(f'<th class="num">{h}</th>' for h in horizons)
    rows = ""
    for e in entries:
        tds = ""
        for h in horizons:
            g = grid.get((e, h))
            if not g:
                tds += '<td class="num">–</td>'
                continue
            tip = (f"{e} entry, {h} hold — n={g['n']}, mean {_f(g['mean'])}, "
                   f"median {_f(g['median'])}, win {g['win']*100:.0f}%, "
                   f"SR {_n(g['sr'])}")
            tds += (f'<td class="num cell" {_tint(g["mean"])} '
                    f'title="{html.escape(tip)}">{_f(g["mean"], 1)}</td>')
        label = {"open": "at open (the trap)"}.get(e, f"{e} after open")
        rows += f'<tr><td class="mono">{html.escape(label)}</td>{tds}</tr>'
    grid_html = f"""
<div class="scroll"><table>
<tr><th>short entry ↓ · hold →</th>{head}</tr>{rows}
</table></div>
<p class="note">Mean net short-side return per event (positive = the fade
wins). The <b>open row is the trap</b>: shorting the listing minute is ruinous
because the first-hour pump runs you over — the edge only exists after it.
Hover any cell for n / median / win rate / Sharpe.</p>"""

    # --- regime bars ----------------------------------------------------------
    max_abs = max((abs(r["mean"]) for r in d["regime"]), default=0.01)
    bars = ""
    for r in d["regime"]:
        hpx = max(4, abs(r["mean"]) / max_abs * 120)
        color = "var(--pos)" if r["mean"] >= 0 else "var(--neg)"
        bars += f"""
<div class="bargrp" title="{r['year']}: n={r['n']}, mean {_f(r['mean'])}, win {r['win']*100:.0f}%">
 <div class="barval">{_f(r['mean'], 1)}</div>
 <div class="barstem" style="height:{hpx:.0f}px;background:{color}"></div>
 <div class="barlbl">{r['year']}</div><div class="barn mono">n={r['n']}</div>
</div>"""
    regime_html = f"""
<div class="bars">{bars}</div>
<p class="note">Net short return per event, cell {html.escape(best_cell)}, by
listing year. Positive every year — but 2023–24 was a soft regime; size
expectations to the lean years, not the fat ones.</p>"""

    # --- futures panel ---------------------------------------------------------
    fx_html = ""
    if fx:
        f1, f2, cov = fx["f1"], fx["f2"], fx["coverage"]
        fx_html = f"""
<div class="eyebrow">Short-side execution — USDⓈ-M futures, funding included (D3)</div>
<div class="tiles">
 <div class="tile"><div class="v pos">{_f(f1.get('mean'))}</div>
  <div class="k">F1: short perp at spot+1h, hold 14d — net of fees, fills
  AND funding (n={f1.get('n','–')}, win {f1.get('win',0)*100:.0f}%)</div></div>
 <div class="tile"><div class="v neg">{_f(fx.get('funding_mean'))}</div>
  <div class="k">avg funding cost per event — negative for the short in
  {fx.get('funding_negative_frac',0)*100:.0f}% of events</div></div>
 <div class="tile"><div class="v">{f1.get('n','–')}/{cov['covered_n']+cov['uncovered_n']}</div>
  <div class="k">listings with a day-one perp — you can only short about 1 in 3</div></div>
 <div class="tile"><div class="v">{_n(f1.get('psr'), 4)}</div>
  <div class="k">PSR vs 0 (pre-registered confirmation; pessimistic
  re-deflation {_n(fx.get('dsr_pessimistic'), 3)} — disclosed)</div></div>
 <div class="tile"><div class="v">{_f(f2.get('mean'))}</div>
  <div class="k">F2 exhibit: enter when the perp launches (≤7d) —
  late entry misses the dump (n={f2.get('n','–')})</div></div>
</div>
<div class="callout"><b>Squeeze tail:</b> worst five events
<span class="mono">{'&nbsp;·&nbsp;'.join(f'{w*100:.0f}%' for w in fx.get('worst5', []))}</span>
of stake. Losses are not capped at −100% in this model. Position sizing is the
difference between this edge and ruin.</div>
<div class="callout info"><b>Coverage bias, disclosed:</b> shortable listings
fade harder on spot ({_f(cov['covered_spot_mean'])}) than unshortable ones
({_f(cov['uncovered_spot_mean'])}) — the +13% is a property of the shortable
subset, not of all listings.</div>"""

    # --- reversion exhibit -----------------------------------------------------
    rev_rows = ""
    for r in d["reversion"]:
        win = "–" if r["win"] is None else f"{r['win']*100:.0f}%"
        rev_rows += (
            f'<tr><td class="mono">{html.escape(r["name"])}</td>'
            f'<td class="num">{r["n"]}</td>'
            f'<td class="num">{_f(r["mean"])}</td>'
            f'<td class="num">{win}</td></tr>')

    # --- forward book ---------------------------------------------------------
    book_rows = ""
    for b in d["book"]:
        status = b["status"]
        cls = ("pass" if status == "SETTLED" else
               "fail" if status.startswith("EXCLUDED") or status == "UNTRADEABLE"
               else "wait")
        book_rows += (
            f'<tr><td class="mono">{html.escape(b["symbol"])}</td>'
            f'<td class="mono">{_ts(b["ft"])}</td>'
            f'<td class="mono">{html.escape(b["perp"] or "–")}</td>'
            f'<td><span class="pill {cls}">{html.escape(status)}</span></td>'
            f'<td class="num">{_f(b["fill"])}</td>'
            f'<td class="num">{_f(b["funding"])}</td>'
            f'<td class="num">{_f(b["total"])}</td>'
            f'<td class="num">{_f(b["spot"])}</td></tr>')

    return f"""<title>Listing Validator — verdicts &amp; forward book</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>{CSS}</style>
<div class="wrap">
<header>
 <h1>Listing Validator</h1>
 <span class="sub">Binance listing-event verdict engine · read-only ·
 no orders, no keys, no capital</span>
 <span class="stamp mono">data through {_ts(s['hi'])} · generated {d['generated']}</span>
</header>

<div class="eyebrow">Verdict ledger</div>
<div class="scroll"><table>
<tr><th>hypothesis</th><th>verdict</th><th>what it means</th></tr>
{ledger_rows}
</table></div>

<div class="eyebrow">What listings actually do — {s['n']} events,
{_ts(s['lo'])} → {_ts(s['hi'])}</div>
{tiles}

<div class="eyebrow">The gauntlet — six ways to kill a ghost</div>
<div class="scroll"><table>
<tr><th>stage</th><th>result</th><th>key statistic</th></tr>
{stage_rows}
</table></div>

<div class="eyebrow">The full grid — every entry × hold combination (nothing cherry-picked)</div>
{grid_html}

<div class="eyebrow">Regime check — does the edge live in one era?</div>
{regime_html}

{fx_html}

<div class="eyebrow">Buy-the-dip exhibit — tested and dead</div>
<div class="scroll"><table>
<tr><th>pre-declared config</th><th class="num">n</th>
<th class="num">mean (long)</th><th class="num">win</th></tr>
{rev_rows}
</table></div>
<p class="note">All four pre-declared post-dump buy configs lose money net.
Buying the crash is just buying the dump earlier.</p>

<div class="eyebrow">Forward paper book — the rule graded on data it has never seen (D4)</div>
<div class="scroll"><table>
<tr><th>listing</th><th>date</th><th>perp</th><th>status</th>
<th class="num">price leg</th><th class="num">funding</th>
<th class="num">total</th><th class="num">spot fade</th></tr>
{book_rows}
</table></div>
<p class="note">Frozen rule, frozen thresholds — forward results are
accounting only and can never be used to re-tune (one-way mirror,
docs/DECISIONS.md D4). Backtest baseline for settled trades:
{_f(0.1323)} per event. CLOSED_PRICE means the price legs are final but
funding is still partial — Binance publishes funding in monthly files, so a
position settles early in the month after it closes.</p>

<div class="foot">
<b>Honesty notes.</b>
<ul>
<li>Verdict confidence is <b>marginal</b>, not overwhelming: deflated Sharpe
0.986 vs the 0.95 bar, one flat walk-forward fold (2023–24), and the
pessimistic re-deflation of the futures leg fails at 0.822 (disclosed above).</li>
<li>Not modeled: liquidation mechanics, borrow limits, exchange outages at
listing minutes. Slippage is a model (range-scaled, capped adverse fills) —
reality can be worse.</li>
<li>A REAL verdict validates a <i>signal</i>, not a deployment. Everything
here is read-only research output.</li>
<li>Methodological rulings are frozen in docs/DECISIONS.md (D1–D4); the full
stage-by-stage numbers are in reports/verdict_report.txt.</li>
</ul>
</div>
</div>"""


def generate(conn, out_paths=("data/dashboard.html", "reports/dashboard.html")):
    d = gather(conn)
    page = render(d)
    for p in out_paths:
        with open(p, "w") as fh:
            fh.write(page)
    return out_paths[0]
